[demo]
start_date = "2005-01-01"
end_date   = "2025-01-01"
rate = { real_seconds_per_month = 0.5 }
seed = 42
users = 10
containers = 20
leaf_rate = { per_real_second = 10 }
rollup = { l0_size=1000, l1_time="1h", l2_time="1d" }
snapshot = { every="P1Y" }
