[build]
# Use a different target directory for Windows to avoid file locking issues
target-dir = "target_windows"

# Force single-threaded compilation to avoid file locking issues
jobs = 1

[target.'cfg(windows)']
# Disable incremental compilation to prevent file locking issues
rustflags = [
    "-C", "incremental=false",
    "-C", "codegen-units=1"
]

[profile.dev]
# Disable incremental compilation in dev profile
incremental = false
codegen-units = 1

[profile.release]
# Disable incremental compilation in release profile
incremental = false
codegen-units = 1
